server:
  port: 8086
  servlet:
    context-path: /

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka/
  instance:
    prefer-ip-address: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html





