version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  api-gateway-service:
    build: ./backend/api-gateway-service
    ports:
      - "${API_GATEWAY_PORT}:8008"
    depends_on:
      - user-service
      - cycletime-service
      - machine-service
      - eureka-discovery-service
      - project-service
    networks:
      - mynetwork

  user-service:
    build: ./backend/user-service
    ports:
      - "${USER_SERVICE_PORT}:8086"
    depends_on:
      - mysql-user-db
      - eureka-discovery-service
    networks:
      - mynetwork

  ai-bot-service:
    build: ./backend/ai-bot-service
    ports:
      - "${AI_BOT_SERVICE_PORT}:8081"
    depends_on:
      - eureka-discovery-service
    networks:
      - mynetwork

  import-service:
    build: ./backend/import-service
    ports:
      - "${IMPORT_SERVICE_PORT}:8089"
    depends_on:
      - eureka-discovery-service
    networks:
      - mynetwork

  project-service:
    build: ./backend/project-service
    ports:
      - "${PROJECT_SERVICE_PORT}:8087"
    depends_on:
      - mysql-project-db
      - eureka-discovery-service
    networks:
      - mynetwork

  cycletime-service:
    build: ./backend/cycle-time-service
    ports:
      - "${CYCLETIME_SERVICE_PORT}:8088"
    depends_on:
      - mysql-cycletime-db
      - eureka-discovery-service
    networks:
      - mynetwork

  machine-service:
    build: ./backend/machine-service
    ports:
      - "${MACHINE_SERVICE_PORT}:8085"
    depends_on:
      - mysql-machine-db
      - eureka-discovery-service
    networks:
      - mynetwork

  mysql-user-db:
    image: mysql:8.0
    container_name: ${MYSQL_USER_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_USER_DB}
    ports:
      - "${MYSQL_USER_PORT}:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-user-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-cycletime-db:
    image: mysql:8.0
    container_name: ${MYSQL_CYCLETIME_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_CYCLETIME_DB}
    ports:
      - "${MYSQL_CYCLETIME_PORT}:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-cycletime-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-machine-db:
    image: mysql:8.0
    container_name: ${MYSQL_MACHINE_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MACHINE_DB}
    ports:
      - "${MYSQL_MACHINE_PORT}:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-machine-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-project-db:
    image: mysql:8.0
    container_name: ${MYSQL_PROJECT_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PROJECT_DB}
    ports:
      - "${MYSQL_PROJECT_PORT}:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-project-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  eureka-discovery-service:
    build: ./backend/eureka-discovery-service
    ports:
      - "${EUREKA_PORT}:8761"
    networks:
      - mynetwork

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    build:
      context: ./cycle-time-ui
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - api-gateway-service
    networks:
      - mynetwork


volumes:
  mysql-user-data:
  mysql-cycletime-data:
  mysql-machine-data:
  mysql-project-data:
