/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoryLogResponse } from '../models/history-log-response';
import { StepResponse } from '../models/step-response';
export interface MachineResponse {
  brand?: string;
  createdAt?: string;
  description?: string;
  historyLogs?: Array<HistoryLogResponse>;
  id?: number;
  name?: string;
  productionLineId?: number;
  steps?: Array<StepResponse>;
  type?: 'AUTOMATIQUE' | 'MANUAL' | 'SEMI_AUTO';
}
