/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MachineRequest {
  brand?: string;
  description?: string;
  name?: string;
  productionLineId?: number;
  type?: 'AUTOMATIQUE' | 'MANUAL' | 'SEMI_AUTO';
}
