/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MachineResponse } from '../models/machine-response';
export interface ProductionLineResponse {
  id?: number;
  description?: string;
  machines?: Array<MachineResponse>;
  name?: string;
}
