/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StepRequest {
  description?: string;
  machineId?: number;
  name?: string;
  orderIndex?: number;
  requiresManualTracking?: boolean;
}
