services:


  machines_db:
    image: mysql:8
    container_name: machines_db
    environment:
      MYSQL_ROOT_PASSWORD: lear123
      MYSQL_DATABASE: machines_db
    ports:
      - "3308:3306"
    volumes:
      - machines_db_data:/var/lib/mysql
    networks:
      - db-network



networks:
  db-network:
    driver: bridge

volumes:
  machines_db_data:
