/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VariantResponse } from '../../models/variant-response';

export interface GetVariant$Params {
  id: number;
}

export function getVariant(http: HttpClient, rootUrl: string, params: GetVariant$Params, context?: HttpContext): Observable<StrictHttpResponse<VariantResponse>> {
  const rb = new RequestBuilder(rootUrl, getVariant.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VariantResponse>;
    })
  );
}

getVariant.PATH = '/api/variants/{id}';
