/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VariantRequest } from '../../models/variant-request';
import { VariantResponse } from '../../models/variant-response';

export interface UpdateVariant$Params {
  id: number;
      body: VariantRequest
}

export function updateVariant(http: HttpClient, rootUrl: string, params: UpdateVariant$Params, context?: HttpContext): Observable<StrictHttpResponse<VariantResponse>> {
  const rb = new RequestBuilder(rootUrl, updateVariant.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VariantResponse>;
    })
  );
}

updateVariant.PATH = '/api/variants/{id}';
