/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImportRowError {
  entityIdentifier: string;
  entityType: string;
  message: string;
  rowNumber: number;
  status: string;
  fieldName?: string;
  problematicValue?: string;
  errorCode?: string;
}
