/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportRowError } from '../models/import-row-error'; // Ensure path is correct

export interface ImportReport {
  errors: Array<ImportRowError>;
  failedImports: number;
  sheetName: string;
  skippedRows: number;
  successfulImports: number;
  totalRowsProcessed: number;
  success: boolean;
  overallMessage: string;
}
