name: Build and Push AI-BOT Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Ai-bot Service JAR with Maven (prod)
        run: ./mvnw clean package -DskipTests -Pprod

      # --- Docker Buildx Setup ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # --- Build and Push Ai-bot Service Docker image ---
      - name: Build and Push Ai-bot Service Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-bot-service:latest # Use the exact service name from docker-compose.yml
          platforms: linux/amd64,linux/arm64

      # --- Trigger deployment in infrastructure repository ---
      - name: Trigger stack deployment on VPS
        uses: peter-evans/repository-dispatch@v3
        with:
          # This PAT_TOKEN  is a GitHub Personal Access Token
          # with 'repo' scope, granted access to your 'my-project-infra' repo.
          token: ${{ secrets.PAT_TOKEN }}

          repository: Lear-co/deployment-infrastructure

          event-type: deploy-service
          # This 'client-payload' passes the service name that was updated to the infra repo.
          # Use the exact service name from your docker-compose.yml (ai-bot-service).
          client-payload: '{"service_name": "ai-bot-service"}'
