/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ProjectRequest } from './models/project-request';
export type { ProjectResponse } from './models/project-response';
export type { VariantRequest } from './models/variant-request';
export type { VariantResponse } from './models/variant-response';
