name: Build and Push CycleTime UI Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------------------------------------------
      # -----------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push CycleTime UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cycle-time-ui:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cycle-time-ui:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cycle-time-ui:cache,mode=max

      - name: Trigger stack deployment on VPS
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Lear-co/deployment-infrastructure
          event-type: deploy-service
          client-payload: '{"service_name": "cycle-time-ui"}'
