/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RagResponse } from '../../models/rag-response';

export interface AskSimple$Params {
      body: {
[key: string]: string;
}
}

export function askSimple(http: HttpClient, rootUrl: string, params: AskSimple$Params, context?: HttpContext): Observable<StrictHttpResponse<RagResponse>> {
  const rb = new RequestBuilder(rootUrl, askSimple.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RagResponse>;
    })
  );
}

askSimple.PATH = '/api/rag/ask-simple';
