/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RagQuery } from '../../models/rag-query';
import { RagResponse } from '../../models/rag-response';

export interface Ask$Params {
      body: RagQuery
}

export function ask(http: HttpClient, rootUrl: string, params: Ask$Params, context?: HttpContext): Observable<StrictHttpResponse<RagResponse>> {
  const rb = new RequestBuilder(rootUrl, ask.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RagResponse>;
    })
  );
}

ask.PATH = '/api/rag/ask';
