/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CycleTime } from './models/cycle-time';
export type { CycleTimeRequest } from './models/cycle-time-request';
