/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StepResponse } from '../../models/step-response';

export interface GetStepsByMachine$Params {
  machineId: number;
}

export function getStepsByMachine(http: HttpClient, rootUrl: string, params: GetStepsByMachine$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StepResponse>>> {
  const rb = new RequestBuilder(rootUrl, getStepsByMachine.PATH, 'get');
  if (params) {
    rb.path('machineId', params.machineId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StepResponse>>;
    })
  );
}

getStepsByMachine.PATH = '/api/steps/machine/{machineId}';
