/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StepRequest } from '../../models/step-request';
import { StepResponse } from '../../models/step-response';

export interface UpdateStep$Params {
  id: number;
      body: StepRequest
}

export function updateStep(http: HttpClient, rootUrl: string, params: UpdateStep$Params, context?: HttpContext): Observable<StrictHttpResponse<StepResponse>> {
  const rb = new RequestBuilder(rootUrl, updateStep.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StepResponse>;
    })
  );
}

updateStep.PATH = '/api/steps/{id}';
