/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariantResponse } from '../models/variant-response';
export interface ProjectResponse {
  description?: string;
  id?: number;
  name?: string;
  productionLineIds?: Array<number>;
  variants?: Array<VariantResponse>;
}
