/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VariantRequest {
  name?: string;
  productionLineIds?: Array<number>;
  projectId?: number;
  status?: string;
}
