/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserLogResponse } from '../../models/user-log-response';

export interface GetUserLogs$Params {
  userId: number;
}

export function getUserLogs(http: HttpClient, rootUrl: string, params: GetUserLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserLogResponse>>> {
  const rb = new RequestBuilder(rootUrl, getUserLogs.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserLogResponse>>;
    })
  );
}

getUserLogs.PATH = '/api/logs';
