/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserLogResponse } from '../../models/user-log-response';

export interface UpdateSeen$Params {
  id: number;
  seen: boolean;
}

export function updateSeen(http: HttpClient, rootUrl: string, params: UpdateSeen$Params, context?: HttpContext): Observable<StrictHttpResponse<UserLogResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSeen.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('seen', params.seen, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserLogResponse>;
    })
  );
}

updateSeen.PATH = '/api/logs/{id}';
