server:
  port: 8089
  servlet:
    context-path: /

spring:
  application:
    name: import-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html




