/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  accountLocked?: boolean;
  code?: string;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  lastName?: string;
  roleName?: 'ADMIN' | 'USER' | 'AUDIT';
  userId?: number;
}
