/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CycleTimeRequest {
  endTime?: string;
  isManual?: boolean;
  lineId?: number;
  theoriticalCycleTime?: {
    'seconds'?: number;
    'zero'?: boolean;
    'nano'?: number;
    'negative'?: boolean;
    'units'?: Array<{
      'durationEstimated'?: boolean;
      'timeBased'?: boolean;
      'dateBased'?: boolean;
    }>;
  };
  clientCycleTime?: {
    'seconds'?: number;
    'zero'?: boolean;
    'nano'?: number;
    'negative'?: boolean;
    'units'?: Array<{
      'durationEstimated'?: boolean;
      'timeBased'?: boolean;
      'dateBased'?: boolean;
    }>;
  };
  machineId?: number;
  projectId?: number;
  recordType?: 'MACHINE' | 'OPERATION';
  startTime?: string;
  status?: string;
  stepId?: number;
  userId?: number;
  variantId?: number;
}
