/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionLineResponse } from '../../models/production-line-response';

export interface GetProductionLine$Params {
  id: number;
}

export function getProductionLine(http: HttpClient, rootUrl: string, params: GetProductionLine$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductionLineResponse>> {
  const rb = new RequestBuilder(rootUrl, getProductionLine.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductionLineResponse>;
    })
  );
}

getProductionLine.PATH = '/api/production-lines/{id}';
