/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionLineResponse } from '../../models/production-line-response';

export interface GetAllProductionLines$Params {
}

export function getAllProductionLines(http: HttpClient, rootUrl: string, params?: GetAllProductionLines$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductionLineResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllProductionLines.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductionLineResponse>>;
    })
  );
}

getAllProductionLines.PATH = '/api/production-lines';
