/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionLineRequest } from '../../models/production-line-request';
import { ProductionLineResponse } from '../../models/production-line-response';

export interface UpdateProductionLine$Params {
  id: number;
      body: ProductionLineRequest
}

export function updateProductionLine(http: HttpClient, rootUrl: string, params: UpdateProductionLine$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductionLineResponse>> {
  const rb = new RequestBuilder(rootUrl, updateProductionLine.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductionLineResponse>;
    })
  );
}

updateProductionLine.PATH = '/api/production-lines/{id}';
