/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportReport } from '../../models/import-report';

export interface ImportExcel$Params {
      body: {
'file': File;
}
}

export function importExcel(http: HttpClient, rootUrl: string, params?: ImportExcel$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: ImportReport;
}>> {
  const rb = new RequestBuilder(rootUrl, importExcel.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: ImportReport;
      }>;
    })
  );
}

importExcel.PATH = '/import/excel';
