/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RetrievedDocument } from '../models/retrieved-document';
export interface RagResponse {
  answer?: string;
  confidence?: number;
  reasoning?: string;
  sources?: Array<RetrievedDocument>;
}
