/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RagQuery {
  context?: string;
  entityTypes?: Array<string>;
  maxResults?: number;
  question?: string;
  similarityThreshold?: number;
}
