/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RetrievedDocument {
  content?: string;
  entityId?: number;
  entityType?: string;
  metadata?: {
[key: string]: {
};
};
  similarity?: number;
}
